[terminal]
osc52 =  "CopyPaste"

[window]
#padding = { x = 15, y = 15 }
dimensions = { columns = 120, lines = 40 }
dynamic_padding = true 
decorations =  "Buttonless"
opacity = 0.98

[scrolling] 
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key  = "K", mods="Control|Shift", action = "ScrollPageUp" },
    { key  = "J", mods = "Control|Shift", action = "ScrollPageDown" },
]

[font]
size = 15
offset = { x = 5, y = 2}
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Normal" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }


[colors.primary]
background = '#1c2023'
foreground = '#c7ccd1'

[colors.cursor]
text = '#1c2023'
cursor = '#c7ccd1'

[colors.normal]
black   = '#1c2023'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#c7ccd1'

[colors.bright]
black   = '#747c84'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#f3f4f5'


